### ISSUE TITLE
[semantic_label_publisher_node-4] process has died [pid 4268, exit code 1,

### ISSUE THREAD

**Issue by threemmm** [fdayoub/ros-semantic-mapper#3]
when I run "roslaunch semantic_mapper run_system_amcl_office.launch" I get some errors like below :
```
Traceback (most recent call last):
  File "/root/catkin_ws/src/semantic_label_publisher/nodes/semantic_label_publisher_node.py", line 26, in <module>
    import caffe
ImportError: No module named caffe
[ INFO] [1501997293.492519656]: Initializing likelihood field model; this can take some time on large maps...
[semantic_label_publisher_node-4] process has died [pid 4268, exit code 1, cmd /root/catkin_ws/src/semantic_label_publisher/nodes/semantic_label_publisher_node.py __name:=semantic_label_publisher_node __log:=/root/.ros/log/f6a09bb8-7a65-11e7-a339-0242ac110002/semantic_label_publisher_node-4.log].
log file: /root/.ros/log/f6a09bb8-7a65-11e7-a339-0242ac110002/semantic_label_publisher_node-4*.log

```

Complete Output  : 
```
... logging to /root/.ros/log/f6a09bb8-7a65-11e7-a339-0242ac110002/roslaunch-9f8a273bd5d9-4195.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://9f8a273bd5d9:43517/

SUMMARY
========

PARAMETERS
 * /amcl/global_frame_id: map
 * /amcl/gui_publish_rate: 10.0
 * /amcl/initial_pose_a: 5.2
 * /amcl/initial_pose_x: 13.512
 * /amcl/initial_pose_y: -21.727
 * /amcl/kld_err: 0.05
 * /amcl/kld_z: 0.99
 * /amcl/laser_lambda_short: 0.1
 * /amcl/laser_likelihood_max_dist: 2.0
 * /amcl/laser_max_beams: 30
 * /amcl/laser_model_type: likelihood_field
 * /amcl/laser_sigma_hit: 0.2
 * /amcl/laser_z_hit: 0.5
 * /amcl/laser_z_max: 0.05
 * /amcl/laser_z_rand: 0.5
 * /amcl/laser_z_short: 0.05
 * /amcl/max_particles: 1000
 * /amcl/min_particles: 500
 * /amcl/odom_alpha1: 0.2
 * /amcl/odom_alpha2: 0.2
 * /amcl/odom_alpha3: 0.8
 * /amcl/odom_alpha4: 0.2
 * /amcl/odom_alpha5: 0.1
 * /amcl/odom_frame_id: odom
 * /amcl/odom_model_type: diff
 * /amcl/recovery_alpha_fast: 0.0
 * /amcl/recovery_alpha_slow: 0.0
 * /amcl/resample_interval: 1
 * /amcl/transform_tolerance: 0.1
 * /amcl/update_min_a: 0.5
 * /amcl/update_min_d: 0.2
 * /rosdistro: indigo
 * /rosversion: 1.11.21
 * /semantic_label_publisher_node/MEAN_FILE_PATH: /docker/mean.npy
 * /semantic_label_publisher_node/MODEL_FILE_PATH: /docker/deploy.pr...
 * /semantic_label_publisher_node/PRETRAINED_PATH: /docker/places.ca...
 * /semantic_label_publisher_node/SUB_CAT_FILE: /docker/my_cats.txt
 * /semantic_label_publisher_node/caffe_root: /root/catkin_ws/s...
 * /semantic_label_publisher_node/image_topic: /camera/rgb/image...
 * /semantic_mapper_node/prob_thres: 0.0

NODES
  /
    amcl (amcl/amcl)
    map_server (map_server/map_server)
    semantic_label_publisher_node (semantic_label_publisher/semantic_label_publisher_node.py)
    semantic_mapper_node (semantic_mapper/semantic_mapper_node)
    throttle (topic_tools/throttle)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[semantic_mapper_node-1]: started with pid [4213]
[ INFO] [1501997291.975827197]: semantic mapper started
process[map_server-2]: started with pid [4214]
process[throttle-3]: started with pid [4257]
process[semantic_label_publisher_node-4]: started with pid [4268]
process[amcl-5]: started with pid [4290]
[ INFO] [1501997293.005784176]: Requesting the map...
[ INFO] [1501997293.049382902]: Received a 4000 X 4000 map @ 0.050 m/pix

Traceback (most recent call last):
  File "/root/catkin_ws/src/semantic_label_publisher/nodes/semantic_label_publisher_node.py", line 26, in <module>
    import caffe
ImportError: No module named caffe
[ INFO] [1501997293.492519656]: Initializing likelihood field model; this can take some time on large maps...
[semantic_label_publisher_node-4] process has died [pid 4268, exit code 1, cmd /root/catkin_ws/src/semantic_label_publisher/nodes/semantic_label_publisher_node.py __name:=semantic_label_publisher_node __log:=/root/.ros/log/f6a09bb8-7a65-11e7-a339-0242ac110002/semantic_label_publisher_node-4.log].
log file: /root/.ros/log/f6a09bb8-7a65-11e7-a339-0242ac110002/semantic_label_publisher_node-4*.log
[ INFO] [1501997293.799674161]: Done initializing likelihood field model.
[ WARN] [1501997309.000936892]: No laser scan received (and thus no pose updates have been published) for 1501997309.000838 seconds.  Verify that data is being published on the /laser topic.
.....
...
..
```

**Comment by Shubodh** [comment]
You need to install Caffe and add the path in your bashrc file.
